import org.bau.Exception
  exception

fun square(x int) int throws exception
  if x > 3_000_000_000
    throw exception('Too large')
  return x * x

x := square(3_000_000_001);
println(x)
catch e
  println(e.message)
